### ISSUE TITLE
Crash with ExU

### ISSUE THREAD

**Issue by sctjkc01** [Vexatos/AsieLib#27] opened 2015-12-10 02:31 UTC
http://pastebin.com/nScGKD3i

I don't know if this is caused on Extra Utilities' side, Computronics, or OpenComputers, but this crash only occurs if ExU, OC, and Computronics is installed.  I came here first only because it lists a definition missing from what appears to be AsieLib - pl/asie/lib/block/BlockBase.

**Comment by Vexatos** [comment] 2015-12-10 05:26
This is indeed caused by ExU. This is a duplicate of asiekierka/Computronics#90 and asiekierka/Computronics#84. Read my responses there for what happens and how to temporarily fix it. I already posted an issue at rwtema/extrautilities#414 over a year ago. Apparently it has never been fixed...

**Closed as completed by Vexatos** 2015-12-10 05:26 UTC
Labels: duplicate, invalid
