### ISSUE TITLE
Outdated API's in AsieLib :(

### ISSUE THREAD

**Issue by itsacorn** [Vexatos/AsieLib#25] opened 2015-08-15 08:44 UTC
Hello asiekierka,i have a Problem:AsieLib has a outdated/incorrect API for GregTech.When i add it,i get this: http://i.imgur.com/el04eyX.png.It is asielib's fault because when iremove it,the error is gone.A log:http://pastebin.com/DTbYFkGz . If you don't fix it please give it to Vexatos so he can fix it. 
Thx in future.

**Comment by Vexatos** [comment] 2015-08-15 09:18
Duplicate of #24. Read my response there.

**Closed as completed by Vexatos** 2015-08-15 09:18 UTC
Labels: duplicate, invalid
