### ISSUE TITLE
AsieLib + GregTech Startup Crash

### ISSUE THREAD

**Issue by ForgottenAngel** [Vexatos/AsieLib#21] opened 2015-03-28 15:07 UTC
Game crashes each time on startup. Only complaint being thrown seems to be between AsieLib and GregTech. 

Crash Log: http://pastebin.com/grenFzsa

Anyone have any ideas how to fix this? :/

**Comment by Vexatos** [comment] 2015-03-28 16:09
Duplicate of asiekierka/Computronics#119 and asiekierka/Computronics#118. Read my responses there.

**Closed as completed by Vexatos** 2015-03-28 16:09 UTC
Labels: duplicate, invalid
